/**
 * openclaw-agent-receipts — Agent Receipts plugin for OpenClaw
 *
 * Generates cryptographically signed, hash-linked action receipts
 * for every tool call the agent makes, creating a tamper-evident
 * audit trail using the Agent Receipts TypeScript SDK.
 */

import { dirname } from "node:path";
import { mkdirSync, statSync } from "node:fs";
import { definePluginEntry } from "./openclaw-types.js";
import { openStore } from "@agnt-rcpt/sdk-ts";

import { resolveConfig, loadOrCreateKeys } from "./config.js";
import { loadCustomMappings, DEFAULT_MAPPINGS, DEFAULT_PATTERNS } from "./classify.js";
import {
  beforeToolCall,
  afterToolCall,
  evictPendingForSession,
  type HookDeps,
  type PendingMap,
} from "./hooks.js";
import { Emitter, defaultSocketPath } from "./emitter.js";
import { resetChain, getChainId, type ChainsMap, type ChainState } from "./chain.js";
import { createQueryReceiptsToolFactory, createVerifyChainToolFactory } from "./tools.js";

export default definePluginEntry({
  id: "openclaw-agent-receipts",
  name: "Agent Receipts",
  description: "Cryptographically signed audit trail for agent actions",

  register(api) {
    const cfg = resolveConfig(api.pluginConfig);

    if (!cfg.enabled) {
      api.logger.info("agent-receipts: plugin disabled via config");
      return;
    }

    // All mutable state lives here, scoped to this plugin instance
    const chains: ChainsMap = new Map<string, ChainState>();
    const pending: PendingMap = new Map();
    let mappings = DEFAULT_MAPPINGS;
    let patterns = DEFAULT_PATTERNS;

    if (cfg.taxonomyPath) {
      const custom = loadCustomMappings(cfg.taxonomyPath);
      mappings = custom.mappings;
      patterns = custom.patterns;
      api.logger.info(`agent-receipts: loaded custom taxonomy from ${cfg.taxonomyPath}`);
    }

    // Init signing keys (generate on first run)
    const keys = loadOrCreateKeys(cfg.keyPath);
    api.logger.info(`agent-receipts: keys loaded from ${cfg.keyPath}`);

    // Open receipt store
    mkdirSync(dirname(cfg.dbPath), { recursive: true });
    const store = openStore(cfg.dbPath);
    api.logger.info(`agent-receipts: receipt store opened at ${cfg.dbPath}`);

    const agentId = api.id;

    // Attempt to create a daemon emitter (fire-and-forget; optional).
    //
    // Off by default: forwarding to the daemon copies raw `input`/`output`
    // JSON across a process trust boundary, which is stricter than the
    // in-process `parameterDisclosure` contract. Operators must opt in via
    // `daemonForwarding: true` (or `{ enabled: true }`).
    //
    // session_id is generated by the emitter (UUID v4) per ADR-0010 OQ4 and
    // remains stable for the lifetime of the plugin instance — including
    // across daemon reconnects. We deliberately do NOT pass api.id here:
    // that is the plugin/agent identifier, not a per-session UUID, and using
    // it would (a) violate the ADR contract and (b) make every plugin
    // instance share the same session_id forever.
    //
    // Drop diagnostics are intentionally NOT wired into api.logger: the
    // daemon being absent is the expected case (e.g. dev workstations
    // without the daemon installed) and would otherwise spam a warn line
    // per tool call. Callers that want drop visibility can construct an
    // Emitter directly with `debugLog`.
    let emitter: Emitter | undefined;
    if (cfg.daemonForwarding.enabled) {
      const socketPath = defaultSocketPath();
      if (!socketPath) {
        api.logger.warn(
          "agent-receipts: daemonForwarding enabled but no socket path is configured on this platform; set AGENTRECEIPTS_SOCKET",
        );
      } else {
        try {
          // Pass the resolved socketPath explicitly so the emitter cannot
          // re-resolve to a different value if env vars change between this
          // check and the constructor call (the logged path must match the
          // one actually used).
          emitter = new Emitter({ socketPath });

          // The emitter dials lazily, so a missing socket only surfaces as a
          // silent per-emit drop. A startup stat gives the operator an early warning.
          try {
            statSync(socketPath);
          } catch (err) {
            const e = err as NodeJS.ErrnoException;
            if (e.code === "ENOENT") {
              api.logger.warn(
                `agent-receipts: daemon forwarding enabled but no socket file at ${socketPath}`,
              );
              api.logger.warn(
                "=> Install and start the daemon: https://github.com/agent-receipts/ar/tree/main/daemon",
              );
            } else {
              api.logger.warn(
                `agent-receipts: daemon forwarding enabled but socket probe failed at ${socketPath}: ${e.message} (${e.code ?? "unknown"})`,
              );
            }
          }

          api.logger.info(
            `agent-receipts: daemon emitter ready (socket=${socketPath}, session_id=${emitter.sessionId})`,
          );
        } catch (err) {
          api.logger.warn(`agent-receipts: daemon emitter unavailable: ${String(err)}`);
        }
      }
    }

    const hookDeps: HookDeps = {
      store,
      privateKey: keys.privateKey,
      verificationMethod: keys.verificationMethod,
      agentId,
      logger: api.logger,
      pending,
      chains,
      mappings,
      patterns,
      parameterDisclosure: cfg.parameterDisclosure,
      emitter,
    };

    // --- Hooks ---

    // Reset chain and clear pending stash on new session
    api.on("session_start", (_event, ctx) => {
      const sessionKey = ctx.sessionKey ?? "default";
      const sessionId = ctx.sessionId;
      resetChain(chains, sessionKey, sessionId);
      evictPendingForSession(pending, sessionKey, sessionId);
      api.logger.info(`agent-receipts: new chain for session ${sessionKey}`);
    });

    // Capture tool call context before execution
    api.on(
      "before_tool_call",
      (event, ctx) => {
        beforeToolCall(event, ctx, hookDeps);
      },
      { priority: 100 }, // Run early to capture timing
    );

    // Create receipt after tool execution
    api.on("after_tool_call", async (event, ctx) => {
      try {
        await afterToolCall(event, ctx, hookDeps);
      } catch (err) {
        api.logger.warn(`agent-receipts: receipt creation failed: ${String(err)}`);
      }
    });

    // --- Tools ---

    const toolDeps = {
      store,
      publicKey: keys.publicKey,
      getChainId: (sessionKey: string, sessionId?: string) =>
        getChainId(chains, sessionKey, sessionId),
    };

    // Register as factory functions (OpenClawPluginToolFactory pattern)
    api.registerTool(createQueryReceiptsToolFactory(toolDeps), {
      name: "ar_query_receipts",
    });

    api.registerTool(createVerifyChainToolFactory(toolDeps), {
      name: "ar_verify_chain",
    });

    // --- Service: clean up store and emitter on shutdown ---

    api.registerService({
      id: "ar-store",
      async start() {
        // Store and emitter are already initialised during register — nothing to do
      },
      async stop() {
        emitter?.close();
        store.close();
        api.logger.info("agent-receipts: receipt store closed");
      },
    });

    api.logger.info("agent-receipts: plugin registered — receipts will be generated for all tool calls");
  },
});
